# Generated by Django 5.2.15 on 2026-06-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
