# Generated by Django 5.2.15 on 2026-06-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='actual_away_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='actual_home_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='predicted_away_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='predicted_home_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='points_awarded',
            field=models.FloatField(default=0),
        ),
    ]
