# Generated by Django 5.2.15 on 2026-06-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_actual_away_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='away_team',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='home_team',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
