# Generated by Django 5.2.15 on 2026-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_away_team_question_home_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='actual_away_goals',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goals — option 2 team (away)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='actual_home_goals',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goals — option 1 team (home)'),
        ),
    ]
